[DEFAULT]

[telegram.bot]
token = 
; seprated with , f.g: 123,456,789
admin_chatids = 
; EN or FA
default_language = FA 

[xui-server]
ip = 
port = 
server_username = 
server_password =
panel_url = 
panel_username = 
panel_password = 
